### ISSUE TITLE
Can't locate path: </home/vagrant/Code/blog/vendor/meccado/carousel-admin/src/Models/Admin/>

### ISSUE THREAD

**Issue by amine8ghandi8amine** [meccado/carousel-admin#1]
when php artisan vendor:publish  --force

**Comment by meccado** [comment]
Thanks you for the issue logged,  i have not tested this  for laravel 5.3, it was developed on laravel 5.2. I will test it an revert.

**Comment by meccado** [comment]
Retested the issue in 5,2, fixed some bugs, will be testing on 5.3 next.

**Comment by meccado** [comment]
Not sure why his threw an error, make sure you add   Meccado\CarouselAdmin\CarouselAdminServiceProvider::class,
$ composer dump-autoload
before publishing. Hope this help
