### ISSUE TITLE
i include it in laravel 5.3

### ISSUE THREAD

**Issue by amine8ghandi8amine** [meccado/carousel-admin#2]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1364 Field 'avatar' doesn't have a default   
  value (SQL: insert into `profiles` (`user_id`, `bio`, `updated_at`, `create  
  d_at`) values (3, , 2017-01-24 21:50:51, 2017-01-24 21:50:51))               
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000]: General error: 1364 Field 'avatar' doesn't have a default   
  value

**Comment by meccado** [comment]
Thanks you for the issue logged,  i have not tested this  for laravel 5.3, it was developed on laravel 5.2. I will test it an revert.

**Comment by meccado** [comment]
Retested the issue in 5,2, fixed some bugs, will be testing on 5.3 next.

**Comment by meccado** [comment]
fixed, thanks
